---
- name: System upgrade
  ansible.builtin.import_tasks: upgrade.yml

- name: Check if reboot required
  ansible.builtin.stat:
    path: "/var/run/reboot-required"
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists
