---
- name: Create 'applications' directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/applications"
    mode: 0644
    state: directory

- name: Generate .env file for sensitive variables
  ansible.builtin.template:
    src: ".env.j2"
    dest: "/home/{{ ansible_user }}/applications/.env"
    mode: 0644

- name: Generate Docker Compose manifest from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/applications/docker-compose.yml"
    mode: 0644

- name: Start 'applications' stack
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/applications"
