---
- name: Create 'applications' directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/applications"
    mode: 0644
    state: directory

- name: Ensure Prometheus data directory exists
  ansible.builtin.file:
    path: "{{ applications_data_directory }}/prometheus"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
    state: directory

- name: Copy Prometheus config
  ansible.builtin.copy:
    src: "files/prometheus.yml"
    dest: "{{ applications_data_directory }}/prometheus/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777

- name: Create Grafana directory
  ansible.builtin.file:
    path: "{{ applications_data_directory }}/grafana"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
    recurse: true
    state: directory
