version: "3"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "443:443"
      - "8080:8080"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.customresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.customresolver.acme.email=karoly.szakaly2000@gmail.com"
      - "--certificatesresolvers.customresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
