---
- name: Install prequisites
  ansible.builtin.apt:
    name: "{{ docker_packages_prequisites }}"
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: "{{ docker_keyrings_dir }}"
    mode: 0755

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "{{ docker_keyrings_dir }}/docker.gpg"

- name: Add Docker repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by={{ docker_keyrings_dir }}/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ docker_packages_core }}"
    update_cache: true
