---
- name: Install prequisites
  ansible.builtin.apt:
    name: "{{ docker_packages_prequisites }}"
    update_cache: true

# - name: Create keyrings directory
#   ansible.builtin.file:
#     path: "{{ docker_keyrings_dir }}"
#     mode: 0755

- name: Add the official Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_download_url }}"
    state: present

- name: Verify GPG key
  ansible.builtin.apt_key:
    id: "{{ docker_gpg_key_id }}"
    state: present

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_keyrings_dir }}/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ docker_packages_core }}"
    update_cache: true
