---
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true
    state: present


- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: "docker"
    version: "6.0.1"
    state: present
