---
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true
    state: present

- name: Install Docker-related modules
  ansible.builtin.pip:
    name:
      - "docker==6.0.1"
      - "docker-compose==1.29.2"
    state: present
